In [2]:
import numpy as np

In [10]:
enc = np.load('../_experiments/2019-02-15 02:06:06.646010/encodings70.npy')

In [11]:
enc

array([[[ 0.9854279 ,  0.98568386, -0.9961921 , -0.9853697 ,
         -0.99649614,  0.9913799 , -0.9912567 ,  0.9932842 ,
         -0.99599075, -0.9953836 , -0.98940945, -0.99570876,
          0.99252295, -0.9911297 , -0.9938185 ,  0.9942226 ,
         -0.9917796 , -0.99493694, -0.9920401 , -0.9930721 ]]],
      dtype=float32)

In [7]:
enc = np.load('../_experiments/2019-02-14 ')

In [8]:
enc

array([11.630313], dtype=float32)

In [13]:
enc = np.load('../_experiments/2019-02-15 02:06:06.646010/encodings70.npy')

In [14]:
enc

array([[[ 0.9854279 ,  0.98568386, -0.9961921 , -0.9853697 ,
         -0.99649614,  0.9913799 , -0.9912567 ,  0.9932842 ,
         -0.99599075, -0.9953836 , -0.98940945, -0.99570876,
          0.99252295, -0.9911297 , -0.9938185 ,  0.9942226 ,
         -0.9917796 , -0.99493694, -0.9920401 , -0.9930721 ]]],
      dtype=float32)